# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: bc7168664067bb3d0f5a4d137c33d8b78e1fe9745bd975b9522346540ccf6b63f4c9d5bd5905cca5c2f30f759e7000a80c51ba9ec84e3f47574c0f97be062b43

test:
  secret_key_base: d1fe36fa08e7301dd5654492dbe0ae9b27117ecc0732e8249b9e142bf76993d9dbad3503ea9e8c7f86a0b03e2ef5ea40112743e47fac57fdc5a983ce27988390

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
